services:
  frontend:
    build: .
    container_name: riml-frontend
    restart: always
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: npm start